# Generated by Django 4.2 on 2025-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_game_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
