# Generated by Django 4.2 on 2025-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_game_genre_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(),
        ),
    ]
