# Generated by Django 4.2 on 2025-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_game_genre_alter_game_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_game',
            field=models.ManyToManyField(blank=True, related_name='user_preferred_game', through='account.UserPreferredGame', to='account.game'),
        ),
    ]
