# Generated by Django 4.2 on 2025-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_game_genre_alter_game_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_game',
            field=models.ManyToManyField(blank=True, related_name='users_preferred_game', through='account.UserPreferredGame', to='account.game'),
        ),
    ]
