# Generated by Django 4.2 on 2025-03-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_preferred_game'),
        ('account', '0007_user_email_verification_token_user_is_verified_and_more'),
    ]

    operations = [
    ]
