# Generated by Django 4.2 on 2025-03-11 07:39

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_nickname_alter_user_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='header_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='필수. 20자 이하. 문자, 숫자 및 @/./+/-/_만 가능.', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(5)], verbose_name='username'),
        ),
    ]
