# Generated by Django 4.2 on 2025-03-13 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
