# Generated by Django 4.2 on 2025-03-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_verification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steam_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
