# Generated by Django 4.2 on 2025-03-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_steam_avatar_user_steam_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='steam_profile_image',
            new_name='steam_profile_url',
        ),
    ]
