# Generated by Django 4.2 on 2025-03-25 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_steam_profile_image_user_steam_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_game',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_genre',
        ),
        migrations.RemoveField(
            model_name='userpreferredgame',
            name='playtime',
        ),
        migrations.AlterField(
            model_name='userpreferredgame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPreferredGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_genres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='UserLibraryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
