# Generated by Django 4.2 on 2025-03-25 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_preferred_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrarygame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
