# Generated by Django 4.2 on 2025-03-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_userlibrarygame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrarygame',
            name='playtime',
            field=models.IntegerField(default=0, help_text='단위: 분'),
        ),
    ]
