# Generated by Django 4.2 on 2025-03-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_is_syncing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='review_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='trailer_url',
        ),
    ]
